services:
  server:
    build:
      context: ./server
    container_name: syndesk-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    build:
      context: ./client
    container_name: syndesk-client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped